### ISSUE TITLE
How to install and use pysamp?

### ISSUE THREAD

**Issue by XCarCedo** [pysamp/PySAMP#36] opened 2020-10-31 19:40 UTC
Someone can help me to install and use "**PySAMP**"?

**Comment by habecker** [comment] 2020-11-02 17:43
Hey, well the README is currently not up to date. I recently updated everything and setup docker. If you've docker installed it is fairly easy to use PySAMP. Just checkout my feat/reload-gamemode/docker branch and run the server.sh script from inside the docker/ directory.

The more classic way to use PySAMP is to follow the Readme with respect to the installation of a 32bit python environment and use the currently more or less outdated PySAMP.dll or PySAMP.so which you can download from: https://github.com/habecker/PySAMP/releases

Then copy the dll or (preferably on linux) so into the plugins directory of your sa-mp server and activate the plugin in the server configuration. Further more, copy the files samples/empty/gamemode.py and samples/empty/samp.py into a python subfolder of your sa-mp server directory. Then run your server and the sample gamemode should be up and running

**Comment by XCarCedo** [comment] 2020-12-25 14:08
Hey, I@habecker sorry to answer for a long time. I use the classic way to use PySAMP I will see everything with python3 64 bits on my system and after running my server I see this error:
![image](https://user-images.githubusercontent.com/69898738/103136716-f2c76980-46d7-11eb-897c-75c4245ad0aa.png)
What's the problem?

**Comment by habecker** [comment] 2020-12-31 14:07
@XCarCedo
Make sure, that you installed the 32-bit Python 3.5m version on your server!
For debian and ubuntu, this should work:
```bash
sudo dpkg --add-architecture i386
sudo apt-get update
```
and then:
```bash
sudo apt install python3-dev:i386
```
For Windows:
You can download 32 bit portable versions and installers from the python.org website.

**Comment by LivioMirandaJr** [comment] 2020-12-31 22:46
Is there a way to use PySAMP without i386 Python? Installing this makes the server run, but it breaks the SSH connection from my Google Cloud VM

**Comment by LivioMirandaJr** [comment] 2021-01-01 06:44
![image](https://user-images.githubusercontent.com/63527139/103434655-558e9880-4be3-11eb-937d-baef7fda3ff9.png)
I'm getting this error using the docker method, without python3:i386. As I said, if I install 32bit Python, my SSH connection with GCP just break and I have to re-install the VM.

**Comment by dennorske** [comment] 2021-01-01 17:30
I am afraid you can not run the plugin without the necessary dependency. Since the SA-MP server is a 32-bit based application, you need the 32-bit python installed.

How are you running it in docker? Docker is preferred as you are no longer depending on the host system to install the dependencies.

**Comment by LivioMirandaJr** [comment] 2021-01-01 22:19
I was running the server.sh from inside docker folder only to build the structure, and then I was trying to run the server using samp03svr from /server, I just realized that I need to keep using the server.sh script from docker folder even after configuring my server lol.

**Comment by LivioMirandaJr** [comment] 2021-01-02 02:52
Is it possible to use both approaches? I already have a pawn GM, can I use it with a Python GM at the same time?

I change the gamemode config in server.cfg but it always revert to "empty" when I run server.sh

As much as I'd love to use Python for this, it will be pretty hard to port everything in my GM

**Comment by LivioMirandaJr** [comment] 2021-01-02 04:19
![image](https://user-images.githubusercontent.com/63527139/103450665-4b7aa180-4c98-11eb-88cc-71a2b4b45375.png)
I wasn't able to create a command, when I tried to print "cmdtext" it returns None, no matter what command I use in-game.

I also tried to use "text" from OnPlayerText, same behavior.

**Comment by dennorske** [comment] 2021-01-02 13:26
It is not possible to run two gamemodes alongside. What the plugin does, it translates the python code over to pawn amx, and runs it live. That means, any other gamemode must be loaded with gmx or config edit. 

@habecker is it possible to run pysamp with filterscripts? 

@LivioMirandaJr I will take a look at that problem, thanks!

**Comment by habecker** [comment] 2021-01-02 14:36
Well, it is possible to run a python and an amx gamemode. Regarding OnPlayerCommandText: I just tested this and it worked. It's important, that the AMX gamemode you use returns 0 here. I think this also applies to all filterscripts. But it's interesting, that you got None. I will look into that.

It should be possible to run all side-by-side. Unfortunately, there is currently a bug regarding /rcon gmx, which results in crashes. I'm still working on that one on the branch feat/reload-gamemode.

**Comment by LivioMirandaJr** [comment] 2021-01-02 16:09
So I suppose I'm still starting the starver the wrong way? I'm using /docker/server.sh to start it, it calls your "check_server_config.py" that change the gamemode to "empty":

            if k == 'gamemode0' and v != 'empty 1':
                v = 'empty 1'

is this an intended behavior? If so, how can I use both amx and python gamemode? Idk if this is important, but I cloned your feat/reload-gamemode branch

About OnPlayerCommandText, the empty.amx doesn't even implement this if it is compiled after /docker/scripts/empty.pwn

**Comment by habecker** [comment] 2021-01-02 16:32
Okay sorry, my mistake .. I can reconstruct the behaviour and I'm working on it. I'm trying to fix it this evening (UTC+1 😄 )

**Comment by LivioMirandaJr** [comment] 2021-01-02 17:28
Last question, I changed my local copy of check_server_config.py so now I can use my AMX gamemode, OnPlayerCommandText is working in Python, however, I created a test command, and even when it works correctly, the server returns SERVER: Unknown Command, any idea why?

It doesn't matter if my function (gamemode.py) returns True or False, it seems that gamemode.amx just don't recognize the response.

**Comment by habecker** [comment] 2021-01-03 11:58
@LivioMirandaJr okay, here you go. I just fixed a couple of issues (including the cmdtext bug) on the branch feat/reload-gamemode. I will not merge it into master until I documented all features (eg. you can reload the python gamemode using rcon cmd "pyreload" now). I hope, it works for you now. Thanks for your bug reports 😄 and feel free to ask more questions, if you have any problems.

**Comment by habecker** [comment] 2021-01-03 12:03
To your newest question: that should not happen. I'll look into that

**Comment by LivioMirandaJr** [comment] 2021-01-03 12:03
@habecker do you have any suggestions regarding the returns issue?

**Comment by habecker** [comment] 2021-01-03 12:07
I'm working on it :)

**Comment by habecker** [comment] 2021-01-03 12:16
It seems to work here, do you use any filterscripts who do not return 0?

**Comment by habecker** [comment] 2021-01-03 13:09
Okay, I fixed it. It happened because of my reimplementation of the callbacks. Now any callback in python with the return value True will prevent filterscripts / gamemode callbacks from getting called. But if the return value is False, they should be able to catch it.

**Comment by LivioMirandaJr** [comment] 2021-01-03 22:05
@habecker I really feel that I'm abusing your patience, and I'm sorry, but I really want to use PySAMP.

I had to change some returns in gamemode.py, gamemode.amx wasn't able to load correctly because of them. I changed OnGameModeInit, OnPlayerSpawn, OnPlayerRequestClass and OnPlayerDisconnect to False and the issue was resolved apparently.

But now I'm getting these errors below, any idea why?

TypeError: OnPlayerInteriorChange() missing 3 required positional arguments: 'playerid', 'newinteriorid', and 'oldinteriorid'
TypeError: OnPlayerEnterCheckpoint() missing 1 required positional argument: 'playerid'

The last one is crashing the server

Many thanks to you for your help, and for developing PySAMP!

EDIT: I found out that the crash occurs when OnPlayerEnterDynamicCP is called from gamemode.amx, I didn't find a workaround, seems like a problem with the Python CallBacks

**Comment by XCarCedo** [comment] 2021-01-05 17:21
> @XCarCedo
> Make sure, that you installed the 32-bit Python 3.5m version on your server!
> For debian and ubuntu, this should work:
> 
> ```shell
> sudo dpkg --add-architecture i386
> sudo apt-get update
> ```
> 
> and then:
> 
> ```shell
> sudo apt install python3-dev:i386
> ```
> 
> For Windows:
> You can download 32 bit portable versions and installers from the python.org website.

i installed again my python and now i installed python version 3.5.1 32bit on my system i tested it and working but when i running server show old error there is images of server directory:
Main Directory:
![image](https://user-images.githubusercontent.com/69898738/103677460-94cc3900-4f97-11eb-9ffd-f57574db380d.png)
server.cfg:
![image](https://user-images.githubusercontent.com/69898738/103677396-7cf4b500-4f97-11eb-9450-169f804f2e9b.png)
plugins:
![image](https://user-images.githubusercontent.com/69898738/103677518-a9103600-4f97-11eb-9eb9-210c214c29a5.png)
and finally python folder:
![image](https://user-images.githubusercontent.com/69898738/103677642-cb09b880-4f97-11eb-8dfb-cfe397a25b56.png)
there is any problem?

**Comment by dennorske** [comment] 2021-01-06 23:10
> i installed again my python and now i installed python version 3.5.1 32bit on my system i tested it and working but when i running server show old error

Could we have a glance at the errors you see? :) That would be helpful determining the cause

**Comment by XCarCedo** [comment] 2021-01-07 09:36
> > i installed again my python and now i installed python version 3.5.1 32bit on my system i tested it and working but when i running server show old error
> 
> Could we have a glance at the errors you see? :) That would be helpful determining the cause

![image](https://user-images.githubusercontent.com/69898738/103876613-1aabc980-50e9-11eb-94f9-fe3f1309ddfb.png)
Failed to load pySAMP plugin :(

**Comment by dennorske** [comment] 2021-01-07 16:26
> > > i installed again my python and now i installed python version 3.5.1 32bit on my system i tested it and working but when i running server show old error
> > 
> > 
> > Could we have a glance at the errors you see? :) That would be helpful determining the cause
> 
> ![image](https://user-images.githubusercontent.com/69898738/103876613-1aabc980-50e9-11eb-94f9-fe3f1309ddfb.png)
> Failed to load pySAMP plugin :(

Do you have the environment paths set up correctly? On windows you need to do this: 
https://datatofish.com/add-python-to-windows-path/

**Comment by XCarCedo** [comment] 2021-01-08 10:56
> > > > i installed again my python and now i installed python version 3.5.1 32bit on my system i tested it and working but when i running server show old error
> > > 
> > > 
> > > Could we have a glance at the errors you see? :) That would be helpful determining the cause
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/69898738/103876613-1aabc980-50e9-11eb-94f9-fe3f1309ddfb.png)
> > Failed to load pySAMP plugin :(
> 
> Do you have the environment paths set up correctly? On windows you need to do this:
> https://datatofish.com/add-python-to-windows-path/

Yes im sure paths working (i tested with cmd)

**Comment by dennorske** [comment] 2021-01-08 13:14
@XCarCedo I will set up an environment tonight to test on Windows, will let you know

**Comment by XCarCedo** [comment] 2021-01-08 13:51
> @XCarCedo I will set up an environment tonight to test on Windows, will let you know

Ok thanks for helping me 😄

**Comment by dennorske** [comment] 2021-01-09 09:13
We're looking into it, as we aren't really able to make the Windows version work either.
Sorry about that!

**Comment by XCarCedo** [comment] 2021-01-09 09:27
> We're looking into it, as we aren't really able to make the Windows version work either.
> Sorry about that!

Ok :(

**Comment by habecker** [comment] 2021-01-09 12:54
Hello again, I got the branch to work with Windows. Here is a build of it:
[PySAMP.zip](https://github.com/habecker/PySAMP/files/5791123/PySAMP.zip)
If you want, you can test this build and give me some feedback. Unfortunately, python 3.5 is no longer supported due to API updates and you need to install python 3.8.6.

**Comment by XCarCedo** [comment] 2021-01-09 15:41
> Hello again, I got the branch to work with Windows. Here is a build of it:
> [PySAMP.zip](https://github.com/habecker/PySAMP/files/5791123/PySAMP.zip)
> If you want, you can test this build and give me some feedback. Unfortunately, python 3.5 is no longer supported due to API updates and you need to install python 3.8.6.

i tested it with lastest samp server windows but again when running server show failed to load plugin :((((((((

**Comment by habecker** [comment] 2021-01-09 18:31
if you run this in console (powershell / cmd / ... ): 
`python.exe -c "import platform; print(platform.architecture(), platform.python_version())"`
What is the output?

**Comment by XCarCedo** [comment] 2021-01-09 19:02
> if you run this in console (powershell / cmd / ... ):
> `python.exe -c "import platform; print(platform.architecture(), platform.python_version())"`
> What is the output?

output : ('64bit', 'WindowsPE') 3.8.6
i tested the new build on my friend system. him get my error to

**Comment by habecker** [comment] 2021-01-10 00:01
If you have the powershell installed (preinstalled on windows 10). You can now use a batch script to automatically download an embedded python into your sa-mp server and then to start the server using the embedded interpreter. Just copy this batch-file: [pysamp-batch.zip](https://github.com/habecker/PySAMP/files/5792002/pysamp-batch.zip) into your sa-mp server directory and start it from there. It first checks if your local python is compatible and if it's not and it's not already downloaded, it downloads one as described. It can then later be used to always start the server with the embedded interpreter.


 I'll release this stuff later

**Comment by XCarCedo** [comment] 2021-01-10 06:04
> If you have the powershell installed (preinstalled on windows 10). You can now use a batch script to automatically download an embedded python into your sa-mp server and then to start the server using the embedded interpreter. Just copy this batch-file: [pysamp-batch.zip](https://github.com/habecker/PySAMP/files/5792002/pysamp-batch.zip) into your sa-mp server directory and start it from there. It first checks if your local python is compatible and if it's not and it's not already downloaded, it downloads one as described. It can then later be used to always start the server with the embedded interpreter.
> 
> I'll release this stuff later

Thanks that working 😄

**Comment by XCarCedo** [comment] 2021-01-10 08:48
emm thats working but every time i want run server need to download again python show this message:
![image](https://user-images.githubusercontent.com/69898738/104118390-fb59aa00-533d-11eb-96ff-12385fba6a31.png)
any way?

**Comment by habecker** [comment] 2021-01-10 12:10
Okay, here is another one 😄 [pysamp-batch.zip](https://github.com/habecker/PySAMP/files/5792551/pysamp-batch.zip)

**Comment by XCarCedo** [comment] 2021-01-10 12:24
> Okay, here is another one 😄 [pysamp-batch.zip](https://github.com/habecker/PySAMP/files/5792551/pysamp-batch.zip)

Thank you @habecker my issues completely fixed

**Comment by habecker** [comment] 2021-01-10 13:27
> @habecker I really feel that I'm abusing your patience, and I'm sorry, but I really want to use PySAMP.
> 
> I had to change some returns in gamemode.py, gamemode.amx wasn't able to load correctly because of them. I changed OnGameModeInit, OnPlayerSpawn, OnPlayerRequestClass and OnPlayerDisconnect to False and the issue was resolved apparently.
> 
> But now I'm getting these errors below, any idea why?
> 
> TypeError: OnPlayerInteriorChange() missing 3 required positional arguments: 'playerid', 'newinteriorid', and 'oldinteriorid'
> TypeError: OnPlayerEnterCheckpoint() missing 1 required positional argument: 'playerid'
> 
> The last one is crashing the server
> 
> Many thanks to you for your help, and for developing PySAMP!
> 
> EDIT: I found out that the crash occurs when OnPlayerEnterDynamicCP is called from gamemode.amx, I didn't find a workaround, seems like a problem with the Python CallBacks

@LivioMirandaJr It should be fixed on branch `feat/reload-gamemode`. So, if you want you could test it. I'll all changes soon, when everything works and is documented

**Closed as completed** 2021-01-24 21:45 UTC
Labels: docs
