### ISSUE TITLE
I got some errors crashing my server

### ISSUE THREAD

**Issue by AhmedMohamed264** [pysamp/PySAMP#45] opened 2021-02-10 17:44 UTC
**Describe the bug**
When i run pysamp-launcher.bat i get some warning messages
here is it
```
 "Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 8, in <module>
ValueError: not enough values to unpack (expected 2, got 1)"
```

but then when i join the server (lorenc SFCNR Gamemode script) i get these errors that crashes the server:

```
"[06:37:39] [sampgdk:warning] Index mismatch for OnVehicleStreamOut (-10059 != -10060)
[06:37:39] [sampgdk:warning] Index mismatch for OnVehicleStreamOut (-10059 != -10060)
[06:37:39] [sampgdk:warning] Index mismatch for OnVehicleStreamOut (-10059 != -10060)
[06:37:39] [sampgdk:warning] Index mismatch for OnVehicleStreamOut (-10059 != -10060)
[06:37:39] [sampgdk:warning] Index mismatch for OnVehicleStreamOut (-10059 != -10060)
[06:37:39] [sampgdk:warning] Index mismatch for OnVehicleStreamOut (-10059 != -10060)
[06:37:39] [sampgdk:warning] Index mismatch for OnVehicleStreamOut (-10059 != -10060)
[06:37:39] [sampgdk:warning] Index mismatch for OnVehicleStreamOut (-10059 != -10060)
[06:37:39] [sampgdk:warning] Index mismatch for OnVehicleStreamOut (-10059 != -10060)"
```
**Expected behavior**
i expect the server to work normally without crash

**Screenshots**
https://cdn.discordapp.com/attachments/798321782800646155/808853611689672724/unknown.png
https://imgur.com/a/mVooWTd

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**
i have some questions as i am new to this pysamp:

How to continue scripting old pwn script using the python plugin?
Is there any way to convert old pwn script to python script?
Is it possible to load pwn script with python script?
How to make a filterscript using python language?

Thanks

**Comment by dennorske** [comment] 2021-02-11 16:08
Hi there!

We will make sure to look into why this is happening for the OnVehicleStreamOut function. 

**As for the other questions;**
1. **How to continue scripting old script using the new python plugin?**
_You can't, sadly. Variables and functions are not shared in between the python and .amx gamemode, so the most beneficial way would be to work on it as an addition to the gamemode you already have, or start over on scratch._
2. **Is there any way to convert old pwn script to python?**
_No, there is no converter to do this, and we are afraid that will have to be done manually._
3. **Is it possible to load pwn script with python script?**
_Yes, you can run your own .amx gamemode AND your python gamemode simultaneously. See point 1 above._
4. **How to make a filterscript using python language**
_Right now, we are not having any specific support for filterscripts. The plugin is intended to mostly replace how gamemodes and server code is handled in general. You can achieve similar results by modifying how the logic works, using python._

**Comment by AhmedMohamed264** [comment] 2021-02-11 16:26
Thanks

**Comment by habecker** [comment] 2021-02-12 18:17
Do you use any plugin besides PySAMP? There might be some version incompatibilities with other plugins using older versions of sampgdk. If you use other plugins, could you name them; then I can look more into it.

**Comment by dennorske** [comment] 2021-02-28 09:34
Hi @AhmedMohamed264 

Any luck getting back to us? :) Would love to know which plugins you are using alongside PySAMP.

**Comment by AhmedMohamed264** [comment] 2021-03-01 14:24
Hello, i am sorry for being inactive but i was so busy getting prepared for my exams...

alright i am going to list all plugins i am using with the version of each.

Plugins:
crashdetect v4.20
mysql R39-6
gvar v1.3
regex v0.2.1 
sscanf v2.8.2
streamer v2.9.3
Whirlpool latest
FCNPC 1.8.2
RouteConnectorPlugin latest
sampcac_server v0.10.0
MapAndreas v1.2.1
TPoker latest
MerRandom v2.1
profiler latest
FileManager v1.5

I hope you can detect the bug :)

**Comment by dennorske** [comment] 2021-03-03 22:00
Thank you very much!

Will look into this.

**Comment by AhmedMohamed264** [comment] 2021-03-03 22:03
Thanks, i hope you fix it.

**Comment by dennorske** [comment] 2021-03-16 21:14
Hi!
It turns out it is a challenge to identify which plugin it could be that causes it. The issue is that sampgdk has changed over the years, and with new syntax and new parameters, it doesn't always match with the newer versions.

The issue you see is not because of our SampGDK version, but rather that one of your plugins hasn't been updated in a long time, hence using an old version of it. (Like 5+ years old version)

We're afraid it is outside of our scope to implement a fix for it as it is mainly an incompatibility issue, and the only thing we could have done anyway is to show a warning when the server starts.

We're sorry for the inconvenience, maybe you are able to identify the bad plugin, and perhaps replace/change/update it? 
Closing this issue

**Closed as completed by dennorske** 2021-03-16 21:14 UTC
Labels: wontfix
